name: Custom Windows Build (Remotik)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Install dependencies and build
        shell: bash
        run: |
          # نصب vcpkg
          git clone https://github.com/Microsoft/vcpkg.git C:/vcpkg
          cd C:/vcpkg
          ./bootstrap-vcpkg.bat
          
          # نصب کتابخانه‌های مورد نیاز
          ./vcpkg install opus:x64-windows
          ./vcpkg install libvpx:x64-windows
          ./vcpkg install x264:x64-windows
          cd -
          
          # تنظیم متغیرهای محیطی
          export VCPKG_ROOT="C:/vcpkg"
          export VCPKG_DEFAULT_TRIPLET=x64-windows
          
          # حذف --locked
          sed -i 's/--locked//g' build.py
          
          # کامپایل
          python3 build.py --portable --flutter

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Remotik-Windows
          path: target/release/rustdesk.exe
