name: Custom Windows Build (Remotik)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: 'C:/vcpkg'
          
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            C:/vcpkg
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build RustDesk Client
        run: |
          # تنظیم متغیر محیطی VCPKG_ROOT
          echo "VCPKG_ROOT=C:/vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "VCPKG_ROOT=C:/vcpkg" >> $env:GITHUB_PATH
          
          # حذف --locked از فایل build.py
          (Get-Content build.py) -replace '--locked', '' | Set-Content build.py
          
          # کامپایل
          python3 build.py --portable --flutter

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Remotik-Windows
          path: target/release/rustdesk.exe
